export { Hero } from "./Hero";
export { Problem } from "./Problem";
export { Solution } from "./Solution";
export { Workshop } from "./Workshop";
export { Instructor } from "./Instructor";
export { Results } from "./Results";
export { Testimonials } from "./Testimonials";
export { Pricing } from "./Pricing";
export { FAQ } from "./FAQ";
export { FinalCTA } from "./FinalCTA";
export { Footer } from "./Footer";
export { WhatsAppButton, FloatingWhatsApp } from "./WhatsAppButton";